---
- name: Configure Environment
  hosts: all
  gather_facts: false
  become: true
  tasks:

    - name: Create group Hillel
      group:
        name: hillel
        state: present

    - name: Create user Student
      user:
        name=student
        group=hillel
        shell=/bin/bash
        password=student_pass
        append=yes
      become: yes
      become_method: "sudo"

    - name: Ensure epel repo present
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Install Apache2
      yum: name=httpd update_cache=yes state=latest
      when: inventory_hostname in groups['app']

    - name: Enable service httpd, and not touch the state
      service:
        name: httpd
        enabled: yes
      when: inventory_hostname in groups['app']

    - name: Install packages
      yum:
        name: ['mariadb-server']
        state: present
      when: inventory_hostname in groups['db']

    - name: Install the Python MySQL Support Libraries
      yum: pkg=MySQL-python state=latest
      when: inventory_hostname in groups['db']

    - name: start mysql server and enable it on reboot
      service: name=mariadb state=started enabled=true
      when: inventory_hostname in groups['db']

    - name: Run services
      service:
        name: mariadb
        state: started
        enabled: yes
      when: inventory_hostname in groups['db']


     - name: Create a new database with name 'ansible_lesson_1'
       mysql_db:
         name: ansible_lesson_1
         login_user: root
         state: present
       when: inventory_hostname in groups['db']
